//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULOS()
        {
            this.REL_CLIENTE_ARTICULO = new HashSet<REL_CLIENTE_ARTICULO>();
            this.REL_TIENDA_ARTICULO = new HashSet<REL_TIENDA_ARTICULO>();
        }
    
        public int ID_ARTICULO { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public double PRECIO { get; set; }
        public byte[] IMAGEN { get; set; }
        public int STOCK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_CLIENTE_ARTICULO> REL_CLIENTE_ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_TIENDA_ARTICULO> REL_TIENDA_ARTICULO { get; set; }
    }
}
