//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VENTAEntities : DbContext
    {
        public VENTAEntities()
            : base("name=VENTAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICULOS> ARTICULOS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<REL_CLIENTE_ARTICULO> REL_CLIENTE_ARTICULO { get; set; }
        public virtual DbSet<REL_TIENDA_ARTICULO> REL_TIENDA_ARTICULO { get; set; }
        public virtual DbSet<TIENDA> TIENDA { get; set; }
    }
}
