//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_CLIENTE_ARTICULO
    {
        public int ID_REL_CLIENTE_ARTICULO { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_ARTICULO { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
